# Generated by Django 5.0.2 on 2025-05-25 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch', models.CharField(default='None', max_length=20, primary_key=True, serialize=False)),
                ('number_of_students', models.IntegerField(default=0)),
                ('number_of_girls', models.IntegerField(default=0)),
                ('number_of_boys', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(default='None', max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(default='Not Specified', max_length=100)),
                ('otp', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_no', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('current_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMappings',
            fields=[
                ('name', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('mapping', models.JSONField(blank=True, default=None, null=True)),
                ('wing_room_capacities', models.JSONField(blank=True, default=None, null=True)),
                ('batch_strengths', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(max_length=100)),
                ('faculty_phone', models.CharField(max_length=10)),
                ('is_hod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('instiId', models.FileField(upload_to='documents/')),
                ('letter', models.FileField(upload_to='documents/')),
                ('payment_proof', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
                ('payment_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('status', models.CharField(default='Pending Faculty Approval', max_length=100)),
                ('comments', models.CharField(default='None', max_length=300)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('wing_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wing_type', models.CharField(max_length=100)),
                ('num_floors', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=1)),
                ('current_capacity', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(default=0)),
                ('room_occupancy', models.IntegerField(default=1)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_for_guests', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.hostel')),
                ('hostel_wing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.wing')),
            ],
        ),
        migrations.CreateModel(
            name='Application_Final',
            fields=[
                ('application', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HMngmnt.application')),
                ('occupied_date_range', models.CharField(default='None', max_length=100)),
                ('hostel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.hostel')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.room')),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('caretaker', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=10)),
                ('student_roll', models.CharField(max_length=15)),
                ('student_year', models.IntegerField(default=None)),
                ('student_batch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.batch')),
                ('student_prev_room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_students', to='HMngmnt.room')),
                ('student_room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.room')),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('warden', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_chief_warden', models.BooleanField(blank=True, default=False, null=True)),
                ('hostel', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HMngmnt.hostel')),
            ],
        ),
    ]
